services:
  - type: web
    name: pocket-penguin-api
    runtime: python
    pythonVersion: 3.11
    plan: free
    rootDir: backend
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      mkdir -p staticfiles
      python manage.py collectstatic --noinput --clear
      python manage.py migrate
    startCommand: gunicorn pocket_penguin.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOST
        value: "pocket-penguin.onrender.com"
